# Photostation configuration
BASE_URL=***SET_BASE_URL***
DERBYNET_ROLE=***SET_USERNAME***
DERBYNET_PASSWORD=***SET_PASSWORD***

# car or head
PHOTO_TYPE=car

# crop percent (40-100)
CROP_PERCENT=100

#Enable/Disable Passed (Car Ready to Race) on Photo Mode Only
AUTO_PASS_ON_UPLOAD=0
